# Write your MySQL query statement below
SELECT 
    DATE_FORMAT(TRANS_DATE, '%Y-%m') AS MONTH,
    COUNTRY, 
    COUNT(ID) AS TRANS_COUNT,
    SUM(IF(STATE = 'APPROVED', 1, 0)) AS APPROVED_COUNT,
    SUM(AMOUNT) AS TRANS_TOTAL_AMOUNT,
    SUM(IF(STATE = 'APPROVED', AMOUNT, 0)) AS APPROVED_TOTAL_AMOUNT
FROM TRANSACTIONS
GROUP BY MONTH, COUNTRY;